package it.ccprogetti.spalleponte.netbeans.view;

import java.io.Serializable;
import org.openide.ErrorManager;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
import progetto.presentation.view.panel.SpallaContainerPanel;

/**
 * Top component which displays something.
 */
final class SpallaViewTopComponent extends TopComponent {
    
    private static SpallaViewTopComponent instance;
    /** path to the icon used by the component and its open action */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";
    
    private static final String PREFERRED_ID = "SpallaViewTopComponent";
    
    private SpallaViewTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(SpallaViewTopComponent.class, "CTL_SpallaViewTopComponent"));
        setToolTipText(NbBundle.getMessage(SpallaViewTopComponent.class, "HINT_SpallaViewTopComponent"));
//        setIcon(Utilities.loadImage(ICON_PATH, true));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link findInstance}.
     */
    public static synchronized SpallaViewTopComponent getDefault() {
        if (instance == null) {
            instance = new SpallaViewTopComponent();
        }
        return instance;
    }
    
    /**
     * Obtain the SpallaViewTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized SpallaViewTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            ErrorManager.getDefault().log(ErrorManager.WARNING, "Cannot find SpallaView component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof SpallaViewTopComponent) {
            return (SpallaViewTopComponent)win;
        }
        ErrorManager.getDefault().log(ErrorManager.WARNING, "There seem to be multiple components with the '" + PREFERRED_ID + "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }
    
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }
    
    public void componentOpened() {
       add( SpallaContainerPanel.getInstance() );
    }
    
    public void componentClosed() {
        // TODO add custom code on component closing
    }
    
    /** replaces this in object stream */
    public Object writeReplace() {
        return new ResolvableHelper();
    }
    
    protected String preferredID() {
        return PREFERRED_ID;
    }
    
    final static class ResolvableHelper implements Serializable {
        private static final long serialVersionUID = 1L;
        public Object readResolve() {
            return SpallaViewTopComponent.getDefault();
        }
    }
    
}
